apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: member-demo
    version: "1.0"
  name: bonus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: member-demo
    spec:
      containers:
        - name: bonus
          image: docker.io/member-demo:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: member-demo
  name: member-demo
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: member-demo
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: member-demo
spec:
  hosts:
    - "*"
  gateways:
    - microservice-gateway
  http:
    - match:
        - uri:
            prefix: /member-demo/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 8080
            host: member-demo.default.svc.cluster.local